name: Build Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package
      - name: Archive artifacts (Floodgate Bungee)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Floodgate Bungee
          path: bungee/target/floodgate-bungee-1.0-SNAPSHOT.jar
      - name: Archive artifacts (Floodgate Bukkit)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Floodgate Bukkit
          path: bukkit/target/floodgate-bukkit-1.0-SNAPSHOT.jar
      - name: Archive artifacts (Floodgate Velocity)
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: Floodgate Velocity
          path: velocity/target/floodgate-velocity-1.0-SNAPSHOT.jar
